spring.application.name=Clasificador-gastos
spring.datasource.url=jdbc:mysql://localhost:3306/clasificador_gastos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.1-8b-instant
groq.api.key=${GROQ_API_KEY}